########################################
# Classes to include in this target
########################################
classes:
  - type.motherbase
  - services.dataplane
  - services.hashicorp
  - services.saltenv

########################################
# override variables defined in any of
# the classes above
########################################
parameters:
  name: motherbase-dev
  compose:
      domain: "local"
      version: "3"
      depends_on:
        - fluentd
      logging:
        driver: fluentd
        options:
          fluentd: localhost:24224
