# base class that should be imported on all cluster classes
#

parameters:

  provider:
    google:
      version: "~> 2.5"

  terraform:
    backend:
      gcs:
        bucket: o3h-terraform-bucket
        prefix: /${name}/
        credentials: ~/.gcp/o3h-dev-cloud.json


  # List of allowed values for different resources
  # These values are used in different assert methods in the templates
  valid_values:

    # Updated list below with:
    # gcloud compute zones list
    zones:
      - europe-west1-b
      - europe-west1-c
